import io
import json
import re
import zipfile
from typing import Any

from app.core.config import settings
from app.models import Agent


def build_agent_zip(agent: Agent) -> io.BytesIO:
    buffer = io.BytesIO()
    safe_name = _safe_filename(agent.name)

    with zipfile.ZipFile(buffer, mode="w", compression=zipfile.ZIP_DEFLATED) as archive:
        archive.writestr("Dockerfile", _dockerfile())
        archive.writestr("docker-compose.yml", _docker_compose(safe_name))
        archive.writestr(".env.example", _env_example())
        archive.writestr("README.md", _readme(agent))
        archive.writestr(
            "config/agent_config.json",
            _json(
                {
                    "id": agent.id,
                    "name": agent.name,
                    "description": agent.description,
                    "model": "gpt-4o-mini",
                    "tools": agent.tools,
                }
            ),
        )
        archive.writestr("config/system_prompt.txt", agent.system_prompt)
        archive.writestr("config/mcp_servers.json", _json(_mcp_servers(agent.tools)))
        archive.writestr("config/tool_policy.json", _json(agent.tool_policy))

    buffer.seek(0)
    return buffer


def _dockerfile() -> str:
    return f"FROM {settings.runtime_base_image}\nCOPY config/ /app/config/\n"


def _docker_compose(service_name: str) -> str:
    return f"""services:
  {service_name}:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
"""


def _env_example() -> str:
    return "OPENAI_API_KEY=\nTAVILY_API_KEY=\nE2B_API_KEY=\n"


def _readme(agent: Agent) -> str:
    return f"""# {agent.name}

Generated by Agentic Studio.

## Run

```bash
cp .env.example .env
docker compose up --build
```

Agent UI/API should be available at http://localhost:8080.
"""


def _mcp_servers(tools: list[str]) -> dict[str, Any]:
    servers: dict[str, Any] = {}
    if "web_search" in tools:
        servers["web_search"] = {
            "command": "python",
            "args": ["-m", "runtime.tools.web_search"],
            "env": {"TAVILY_API_KEY": "${TAVILY_API_KEY}"},
        }
    if "run_code" in tools:
        servers["run_code"] = {
            "command": "python",
            "args": ["-m", "runtime.tools.run_code"],
            "env": {"E2B_API_KEY": "${E2B_API_KEY}"},
        }
    return servers


def _json(payload: Any) -> str:
    return json.dumps(payload, indent=2, ensure_ascii=False)


def _safe_filename(value: str) -> str:
    normalized = re.sub(r"[^a-zA-Z0-9_-]+", "-", value.strip().lower())
    return normalized.strip("-") or "agent"

